- hosts: localhost
  connection: local
  vars:
    home: "{{ lookup('env', 'HOME') }}"
    personal: $personal
  pre_tasks:
  - name: Update Apt
    become: true
    apt:
      force_apt_get: true
      update_cache: true
      state: present
  tasks:
    become: true
    # - include: tasks/general.yml
    # - include: tasks/cac_setup.yml
    # - include: tasks/c.yml
    # - include: tasks/python.yml
    # - include: tasks/golang.yml
    # - include: tasks/node.yml
    # - include: tasks/docker.yml
  tasks:
    - include: tasks/personal.yml
      when: personal == 1
