- name: Install Docker Prerequisits
  apt:
    name: [ca-certificates, curl, gnupg, lsb-release]
  become: true

- name: Add Docker GPG Key
  shell: mkdir -p /etc/apt/keyrings && curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg

- name: Setup Docker Repository
  shell: echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

- name: Install Docker Engine
  apt:
    update_cache: true
    name: [docker-ce, docker-ce-cli, containerd.io, docker-compose-plugin]
  become: true
