- name: Install General Utilities
  - ansible.builtin.debug:
        msg: This is a test for General Utilities!
  apt:
    name: [
      gnome-tweaks,
      gnome-screenshot,
      git,
      dconf*,
      build-essential,
      strace,
      valgrind,
      curl,
      wget,
      tree,
      net-tools,
      wireshark,
      htop,
      openssh-client,
      google-chrome-stable,
      slack-desktop,
      discord
    ]
- name: Install Jetbrains Toolbox
  become: true
  shell: chmod +x ./scripts/getlatestjbtoolbox.sh && ./scripts/getlatestjbtoolbox.sh
